name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
      
    - name: Verify Java version
      run: java -version

    - name: Build with Gradle
      run: ./gradlew build

    - name: Package Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: my-app
        path: app/build/outputs/apk/release/my-app-release.apk
